#pragma once

#define ALLOW_MULTIPLE_INSTANCES 1

#define ALLOW_NON_PROFILED_LOGIN 1

#define NEXT_GEN_MP 1

#define NGMP_EOS_PRODUCT_ID "BRING_YOUR_OWN"
#define NGMP_EOS_SANDBOX_ID "BRING_YOUR_OWN"
#define NGMP_EOS_ENCRYPTION_KEY "BRING_YOUR_OWN"
#define NGMP_EOS_DEPLOYMENT_ID "BRING_YOUR_OWN"
#define NGMP_EOS_CLIENT_ID "BRING_YOUR_OWN"
#define NGMP_EOS_CLIENT_SECRET "BRING_YOUR_OWN"